# Generated by Django 4.2.16 on 2026-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="分类名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "图书分类",
                "verbose_name_plural": "图书分类",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(max_length=13, unique=True, verbose_name="ISBN"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="书名")),
                ("author", models.CharField(max_length=255, verbose_name="作者")),
                (
                    "publisher",
                    models.CharField(blank=True, max_length=255, verbose_name="出版社"),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="出版日期"),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                ("cover_image", models.URLField(blank=True, verbose_name="封面链接")),
                (
                    "total_copies",
                    models.PositiveIntegerField(default=1, verbose_name="总册数"),
                ),
                (
                    "available_copies",
                    models.PositiveIntegerField(default=1, verbose_name="可借册数"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="馆藏位置"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可借"),
                            ("borrowed", "已借出"),
                            ("reserved", "已预约"),
                            ("maintenance", "维护中"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="books",
                        to="books.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "图书",
                "verbose_name_plural": "图书",
                "ordering": ["-created_at"],
            },
        ),
    ]
