# Generated by Django 4.2.16 on 2026-05-26 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="会员类型"
                    ),
                ),
                (
                    "max_borrow_days",
                    models.IntegerField(default=30, verbose_name="最大借阅天数"),
                ),
                (
                    "max_renew_times",
                    models.IntegerField(default=2, verbose_name="最大续借次数"),
                ),
                (
                    "fine_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=5,
                        verbose_name="每日罚款",
                    ),
                ),
                (
                    "max_borrow_count",
                    models.IntegerField(default=5, verbose_name="最大借阅数量"),
                ),
            ],
            options={
                "verbose_name": "借阅配置",
                "verbose_name_plural": "借阅配置",
            },
        ),
        migrations.CreateModel(
            name="BorrowingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="借阅日期"),
                ),
                ("due_date", models.DateTimeField(verbose_name="应还日期")),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="归还日期"
                    ),
                ),
                (
                    "renew_count",
                    models.IntegerField(default=0, verbose_name="续借次数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrowed", "借出"),
                            ("returned", "已还"),
                            ("overdue", "逾期"),
                            ("lost", "丢失"),
                        ],
                        default="borrowed",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "fine_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="罚款金额",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowing_records",
                        to="books.book",
                        verbose_name="图书",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowing_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="借阅人",
                    ),
                ),
            ],
            options={
                "verbose_name": "借阅记录",
                "verbose_name_plural": "借阅记录",
                "ordering": ["-borrow_date"],
            },
        ),
    ]
